# Nombre del microservicio de proyectos
spring.application.name=ms-proyectos

# Puerto 8081 - el BFF lo llamará en http://localhost:8081
server.port=8081

# Base de datos H2 en memoria para proyectos
spring.datasource.url=jdbc:h2:mem:proyectosdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate crea las tablas automáticamente al iniciar
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Consola H2 accesible en http://localhost:8081/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Necesario en Docker para entrar a H2 desde el navegador de Windows.
spring.h2.console.settings.web-allow-others=true
