# Nombre del API Gateway
spring.application.name=api-gateway

# Puerto 8085 - punto de entrada único para todos los servicios
# El frontend podría llamar al gateway en vez del BFF directamente
server.port=8085

# Configuración de rutas del Gateway
# El Gateway redirige las peticiones al microservicio correcto

# Ruta para autenticación -> ms-auth (8083)
spring.cloud.gateway.routes[0].id=ms-auth
spring.cloud.gateway.routes[0].uri=http://localhost:8083
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

# Ruta para proyectos -> ms-proyectos (8081)
spring.cloud.gateway.routes[1].id=ms-proyectos
spring.cloud.gateway.routes[1].uri=http://localhost:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/proyectos/**

# Ruta para recursos -> ms-recursos (8082)
spring.cloud.gateway.routes[2].id=ms-recursos
spring.cloud.gateway.routes[2].uri=http://localhost:8082
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/recursos/**

# Ruta para BFF -> bff (8084)
spring.cloud.gateway.routes[3].id=bff
spring.cloud.gateway.routes[3].uri=http://localhost:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/bff/**