# Nombre del BFF
spring.application.name=bff

# Puerto 8084 - funciona tanto en casa como en el Duoc
# 8080 está bloqueado en el Duoc, por eso usamos 8084
server.port=8084

# URLs de los microservicios que el BFF consume
ms.proyectos.url=http://localhost:8081/api/proyectos
ms.recursos.url=http://localhost:8082/api/recursos
ms.tareas.url=http://localhost:8086/api/tareas
