# Nombre del BFF
spring.application.name=bff

# Puerto 8080 en casa, 8083 en el Duoc
# Cambia a 8083 si estás en el Duoc
server.port=8080

# URLs de los microservicios que el BFF consume
ms.proyectos.url=http://localhost:8081/api/proyectos
ms.recursos.url=http://localhost:8082/api/recursos