# Nombre del microservicio de autenticación
spring.application.name=ms-auth

# Puerto 8083 - usado porque 8080 está ocupado en el Duoc
# En casa puedes usar 8080 si quieres, pero 8083 funciona en ambos lados
server.port=8083

# URL de la base de datos H2 en memoria
# "mem:authdb" significa que vive en RAM, no en disco
# Se borra cuando se apaga el servidor (perfecta para desarrollo)
spring.datasource.url=jdbc:h2:mem:authdb

# Driver que usa Java para conectarse a H2
spring.datasource.driver-class-name=org.h2.Driver

# Usuario por defecto de H2
spring.datasource.username=sa

# H2 no requiere contraseña por defecto
spring.datasource.password=

# create-drop: crea las tablas al iniciar y las elimina al apagar
# Hibernate lee las entidades (@Entity) y genera el SQL automáticamente
spring.jpa.hibernate.ddl-auto=create-drop

# Muestra el SQL que ejecuta Hibernate en la consola
# Útil para ver qué consultas se están haciendo
spring.jpa.show-sql=true

# Habilita la consola web de H2
# Permite ver la base de datos en el navegador
spring.h2.console.enabled=true

# Ruta para acceder a la consola H2
# Accesible en http://localhost:8083/h2-console
spring.h2.console.path=/h2-console

# Necesario cuando el servicio corre en Docker.
# Permite abrir H2 desde el navegador del computador anfitrion.
spring.h2.console.settings.web-allow-others=true
