# Nombre del microservicio de recursos humanos
spring.application.name=ms-recursos

# Puerto 8082 - el BFF lo llamará en http://localhost:8082
server.port=8082

# Base de datos H2 en memoria para recursos
spring.datasource.url=jdbc:h2:mem:recursosdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate crea las tablas automáticamente
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Consola H2 en http://localhost:8082/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console